from datetime import datetime
from pydantic import BaseModel, Field

class Finding(BaseModel):
    id: str
    scan_id: str = Field(...)
    scanner: str = Field(...) # secret, sast, dependency, config
    rule_id: str = Field(...)
    title: str = Field(...)
    description: str = Field(...)
    severity: str = Field(...)  # critical, high, medium, low, info
    file_path: str = Field(...)
    line_number: int | None
    evidence: str | None
    recommendation: str
    ai_explanation: str | None  # generated by your Groq model
    ai_fix: str | None  # generated fix suggestion
    status: str = Field(...) # open, resolved, ignored
    created_at: datetime